### ISSUE TITLE
Prefect UI unusable where there is no internet access

### ISSUE THREAD

**Issue by jamescoleuk** [PrefectHQ/ui#356] opened 2020-10-20 09:29 UTC
## Description
I'm deploying Prefect to an environment with no Internet access. Strange but true! The UI requests the following URLs that are not available:

`https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700|Material+Icons|Material+Icons+Outlined`
`https.kit.fontawesome.coim/f222ce9ce9.js`

These are fonts and icons. The missing Roboto font is probably fine, but the missing icons (Font Awesome) means all the icons in the UI are replaced with the icon's text identifiers. Everything is crowded and cannot be used.

For public-facing apps it's entirely sensible to use CDNs, but that cannot work for me. Might you be able to bundle the fonts into the build instead of referencing external URLs?

**Comment by joshmeek** [comment] 2020-10-20 11:26
@jamescoleuk Transferred to the UI repo 🙂

**Comment by znicholasbrown** [comment] 2020-10-20 13:34
Thanks for opening this issue @jamescoleuk - I'm closing as it's a duplicate of #91. There's a response there and some steps you can take to update the UI to work without an internet connection.

**Closed by znicholasbrown** 2020-10-20 13:34 UTC

**Comment by jamescoleuk** [comment] 2020-10-20 14:20
Thanks @znicholasbrown. I'm afraid I'm not clear on the steps to make it work without an internet connection. All I can see are "download the fonts manually and copy them to the container". Copy to where in the container? Why would that stop the browser trying to get to fontawesome.com? There's also a link in that comment (https://easyupload.io/ofkue2) but it gets a 404. Is that what I'm missing?

**Comment by znicholasbrown** [comment] 2020-10-20 14:38
@jamescoleuk - you'll copy them to the `/var/www/` directory and modify the import tags in `index.html` to point to the files in the container instead of the CDNs. Then when that file is served, your browser knows to look for relative imports instead of internet ones.

**Comment by jamescoleuk** [comment] 2020-10-20 15:23
Thank you for those details. That works fine but what I have now is more mandrolic and fragile than I'd like. I'd love to see this issue added to the roadmap.
